import type { FacilityEconomySpec, FacilityId, ShipProjectStage } from './types'
export const facilityEconomySpecs: Record<FacilityId, FacilityEconomySpec> = {
  E1: {
    id: 'E1',
    code: 'E1',
    name: '日冕能源署',
    subtitle: '太渊光伏 · 基础电力',
    role: 'energy',
    unlockYear: 0,
    requiredTech: 'TE1-0',
    maxLevel: 15,
    baseUpgradeCost: { regolith: 2, alloy: 1 },
    yieldGrowth: 0.06,
    priority: 10,
    reserveFloor: { power: 14 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '月面第一座能源设施。太渊的金光被光伏阵列截获，转化为维持殖民地的最低电力。陈林看着仪表盘上的数字，想起署里报告里写的"展示存在"。',
    productionMethods: [
      { id: 'ME1-1', name: '光伏发电', input: {}, output: { power: 6 }, note: '无资源输入，截获太渊金光输出电力。月面上唯一不需要还债的东西。' },
      { id: 'ME1-2', name: '纳米光催化发电', input: { water: 0.6 }, output: { power: 6, oxygen: 1.2 }, unlockedBy: 'TE1-1', note: 'TE1-1 解锁后，以水资源催化光反应，额外产出氧气。像在石头上逼出一口气。' },
    ],
  },
  E2: {
    id: 'E2',
    code: 'E2',
    name: '月冕能源署',
    subtitle: 'He3 聚变 · 中期电力',
    role: 'energy',
    unlockYear: 8,
    requiredTech: 'TE2-0',
    maxLevel: 12,
    baseUpgradeCost: { regolith: 3, alloy: 3, currency: 2 },
    yieldGrowth: 0.07,
    priority: 9,
    reserveFloor: { power: 16, regolith: 10 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: 'He3 聚变发电需要消耗月壤。陈林在审批扩建时曾自言自语："挖脚下的土来点火，这算不算在烧自己的船。"',
    productionMethods: [
      { id: 'ME2-1', name: 'He3 聚变发电', input: { regolith: 1.4 }, output: { power: 8 }, note: '消耗月壤，点燃聚变，输出电力。月壤烧一格少一格。' },
    ],
  },
  E3: {
    id: 'E3',
    code: 'E3',
    name: '归元装置',
    subtitle: '微型黑洞 · 外星能源',
    role: 'energy',
    unlockYear: 36,
    requiredTech: 'TE3-0',
    maxLevel: 10,
    baseUpgradeCost: { alloy: 8, quantumCore: 2, currency: 6 },
    yieldGrowth: 0.1,
    priority: 8,
    reserveFloor: { power: 12, quantumCore: 1 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '由外星科技解锁的禁忌能源。以微型黑洞压缩物质获取能量，不消耗资源。陈林第一次看到它运转时，想起封君律——有些东西不需要还债，但代价在别处。',
    productionMethods: [
      { id: 'ME3-1', name: '微型黑洞压缩', input: {}, output: { power: 10 }, unlockedBy: 'TE3-0', note: 'TE3-0 解锁。微型黑洞压缩物质输出电力，不消耗库存资源。欧里说这是轨道鲸一族的送嫁之物。' },
    ],
  },
  C1: {
    id: 'C1',
    code: 'C1',
    name: '静海采掘署',
    subtitle: '月面采掘 · 水 · 月壤',
    role: 'extraction',
    unlockYear: 0,
    requiredTech: 'TC1-0',
    maxLevel: 15,
    baseUpgradeCost: { regolith: 2, alloy: 1 },
    yieldGrowth: 0.05,
    priority: 8,
    reserveFloor: { power: 10 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '本地月面开采设施。静海是月面上一片平坦的灰色尘壤盆地，陈林给它起的名——他需要一个看起来像地名的东西写进述职报告。',
    productionMethods: [
      { id: 'MC1-1', name: '静海月面采掘', input: { power: 1 }, output: { water: 1.6, regolith: 3.9 }, note: '静海表示在本地月面开采。消耗电力，从尘壤中榨出水和月壤。' },
    ],
  },
  C2: {
    id: 'C2',
    code: 'C2',
    name: '西海采掘署',
    subtitle: '小行星带远征 · 合金',
    role: 'extraction',
    unlockYear: 10,
    requiredTech: 'TC2-0',
    maxLevel: 12,
    baseUpgradeCost: { alloy: 3, currency: 3 },
    yieldGrowth: 0.06,
    priority: 8,
    reserveFloor: { power: 10, water: 6, oxygen: 6, biomass: 4 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '小行星带远征采掘设施。西海不在月面上，是太渊引力阱内一条富矿碎屑带。远征队伍每往返一次，陈林就要在轮换名册上多签一个名字。',
    productionMethods: [
      { id: 'MC2-1', name: '西海小行星带采掘', input: { power: 1.4, water: 0.3, oxygen: 0.4, biomass: 0.2 }, output: { water: 1.2, regolith: 3.1, alloy: 1.2 }, note: '西海表示在小行星带开采。额外消耗水、氧气和生物质维持远征队，产出水、月壤与合金。' },
      { id: 'MC2-2', name: '生态行星资源采集', input: { power: 1.4 }, output: { water: 1.2, regolith: 3.1, alloy: 1.2 }, unlockedBy: 'TC2-2', note: 'TC2-2 外星科技解锁。阿缇娅的坐标核指向一颗活着的生态行星，远征队不再需要携带生命维持补给。' },
    ],
  },
  B: {
    id: 'B',
    code: 'B',
    name: '水培生态球',
    subtitle: '生命维持 · 氧气 · 生物质',
    role: 'life',
    unlockYear: 4,
    requiredTech: 'TB-0',
    maxLevel: 15,
    baseUpgradeCost: { alloy: 2, water: 3, regolith: 3 },
    yieldGrowth: 0.07,
    priority: 10,
    reserveFloor: { water: 10, oxygen: 12, biomass: 8 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '月面上唯一像活物的东西。水培生态球在灰冷的地表上发出微弱的绿光，陈林有时会在夜里去看它，假装月面还有春天。',
    productionMethods: [
      { id: 'MB-1', name: '水培生态循环', input: { water: 0.8 }, output: { oxygen: 2.6, biomass: 1.8 }, note: '消耗水，在球体内培育藻膜，产出氧气与生物质。水是这颗卫星上最贵的奢侈品。' },
      { id: 'MB-2', name: '无水栽培循环', input: { regolith: 0.6 }, output: { oxygen: 2.6, biomass: 1.8 }, unlockedBy: 'TB-2', note: 'TB-2 解锁。梅露的孢囊教会了生态球吃月壤而不是水——以略低价值的代价换一口气。' },
    ],
  },
  F: {
    id: 'F',
    code: 'F',
    name: '天工精炼署',
    subtitle: '工业精炼 · 合金 · 星海货币',
    role: 'industry',
    unlockYear: 12,
    requiredTech: 'TF-0',
    maxLevel: 12,
    baseUpgradeCost: { regolith: 4, alloy: 3, currency: 2 },
    yieldGrowth: 0.07,
    priority: 8,
    reserveFloor: { power: 10, regolith: 10 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '月壤进去，合金出来。天工精炼署是月面唯一像工厂的东西，陈林路过时总能闻到一股灼烧月壤的焦味。',
    productionMethods: [
      { id: 'MF-1', name: '天工精炼', input: { power: 1.2, regolith: 1.6 }, output: { alloy: 2.2, oxygen: 0.4 }, note: '消耗电力与月壤，精炼产出合金与少量氧气。月壤烧出来的合金，带着一股灰味的纯。' },
      { id: 'MF-2', name: '重原子炼金', input: { power: 1.2, regolith: 1.6 }, output: { alloy: 2.2, oxygen: 0.4, currency: 1.0 }, unlockedBy: 'TF-1', note: 'TF-1 外星科技解锁。塔罗的炼金注释让精炼炉学会了从月壤里榨出星海货币——不是策略切换，是额外的馈赠。' },
    ],
  },
  P: {
    id: 'P',
    code: 'P',
    name: '伊犁河谷',
    subtitle: '生态培育 · 生物质 · 氧气',
    role: 'ecology',
    unlockYear: 14,
    requiredTech: 'TP-0',
    maxLevel: 12,
    baseUpgradeCost: { water: 4, regolith: 3, alloy: 2 },
    yieldGrowth: 0.05,
    priority: 7,
    reserveFloor: { water: 10, biomass: 8, regolith: 8 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '阶梯式河谷培育床。陈林给它取了一个地球上某个河谷的名字，同事问他为什么，他说随便取的。没人追问。',
    productionMethods: [
      { id: 'MP-1', name: '河谷生态培育', input: { regolith: 1, water: 0.6 }, output: { biomass: 1.8, oxygen: 1.2 }, note: '默认生产方式。消耗月壤和水，在阶梯上培育生态，产出生物质与氧气。' },
      { id: 'MP-2', name: '合金作物', input: { regolith: 1, water: 0.6 }, output: { biomass: 1.0, oxygen: 0.8, alloy: 0.4 }, unlockedBy: 'TP-1', note: 'TP-1 外星科技解锁。合金作物产出较少生物质和氧气，但额外产出合金——在河谷里长出金属，像一颗种子记住了矿脉。' },
    ],
  },
  R: {
    id: 'R',
    code: 'R',
    name: '月穹生态环',
    subtitle: '分阶段生态改造',
    role: 'ecology',
    unlockYear: 18,
    requiredTech: 'TR-0',
    maxLevel: 10,
    baseUpgradeCost: { water: 8, biomass: 8, alloy: 12 },
    yieldGrowth: 0.05,
    priority: 11,
    reserveFloor: { water: 12, oxygen: 12, biomass: 10 },
    interfaceDuty: '特殊设施页展示四阶段工程进度、投入与回报。',
    note: '投资型项目：前期吸收多余资源，中期集中投入，后期释放产出。',
    productionMethods: [
      { id: 'MR-1', name: '气候改造装置建设', input: { power: 10, water: 1.2, oxygen: 2.4, biomass: 2.2, regolith: 2.8, alloy: 2.2 }, output: {}, condition: '默认阶段', note: '把公共库存转化为生态工程进度。该阶段消耗电力、气体、基质和合金，不产出普通库存资源。' },
      { id: 'MR-2', name: '大气改造', input: { oxygen: 3 }, output: {}, condition: '阶段推进', autoSelect: false, note: '投入大量氧气。' },
      { id: 'MR-3', name: '生态改造', input: { water: 3.6, regolith: 2.4, biomass: 2 }, output: {}, condition: '阶段推进', autoSelect: false, note: '投入水、月壤和生物质。' },
      { id: 'MR-4', name: '回报阶段', input: {}, output: { water: 2.4, oxygen: 2.6, biomass: 2.1 }, condition: '阶段推进', autoSelect: false, note: '没有资源消耗，随进度提高逐渐产出。' },
    ],
    phaseNotes: [
      { name: '气候改造装置建设阶段', note: '投入合金和能源，没有产出。' },
      { name: '大气改造阶段', note: '需要投入大量氧气。' },
      { name: '生态改造阶段', note: '需要投入大量水，以及一定的月壤和生物质。' },
      { name: '回报阶段', note: '没有资源消耗，随着进度提高逐渐产出；解锁科技可以加速推进。' },
    ],
  },
  S: {
    id: 'S',
    code: 'S',
    name: '星海交易港',
    subtitle: '双向贸易 · 手动采购 · 自动保护',
    role: 'trade',
    unlockYear: 20,
    requiredTech: 'TS-0',
    maxLevel: 1,
    baseUpgradeCost: {},
    yieldGrowth: 0.05,
    priority: 6,
    reserveFloor: { currency: 8, power: 10 },
    interfaceDuty: '展示双向贸易、批量采购、自动购入保护与债务风险。',
    note: '特殊贸易节点。星海交易港不占用居民岗位，也不通过扩建提升等级；它是月面与外界唯一的商业接口，所有价值都体现在交易决策里。',
    productionMethods: [
      { id: 'MS-1', name: '贸易结算', input: {}, output: {}, note: '不产生固定日净值。双向贸易由市场与自动购买规则处理。' },
    ],
    phaseNotes: [
      { name: '双向贸易', note: '已解锁的星港贸易品类均可双向处理。买进来的是活路，卖出去的是面子。' },
      { name: '手动补充', note: '可以手动补充已开放贸易品类。陈林偶尔会亲自补一单，算是行使王权。' },
      { name: '自动购买', note: '星海货币赤字时暂停，恢复盈余后继续。没钱就不买，这是月面上唯一讲道理的规矩。' },
    ],
  },
  K: {
    id: 'K',
    code: 'K',
    name: '月面王城',
    subtitle: '人口 · 税收 · 王月报告',
    role: 'government',
    unlockYear: 0,
    requiredTech: 'TK-0',
    maxLevel: 15,
    baseUpgradeCost: { regolith: 3, alloy: 2 },
    yieldGrowth: 0.08,
    priority: 10,
    reserveFloor: { population: 10 },
    interfaceDuty: '展示人口、税收与上一轮王月执行报告。',
    note: '月面王城是陈林的龙椅所在。它同时是人口建筑、税收来源和王月报告归档处。陈林大部分时间坐在这里，不是因为他想，是因为封君律不让他站起来。',
    productionMethods: [
      { id: 'MK-1', name: '王城安置与税收', input: { water: 0.4, oxygen: 0.3, biomass: 0.3 }, output: { population: 1.2, currency: 0.8 }, note: '前期人口容量建筑。居民生命维持消耗水、氧气和生物质；人口增长与税收由全局人口系统结算。' },
    ],
    phaseNotes: [
      { name: '人口', note: '月面王城是前期人口建筑。住进来的人都知道王上走不了，但他们自己半年后可以走。' },
      { name: '税收', note: '通过征税获得铸币权，星海货币与人口成正比。陈林收的不是税，是签字的代价。' },
      { name: '王月报告', note: '每 50 御日归档一次阶段报告，汇总人口、GDP、资源产消与三项方向性建议。' },
    ],
  },
  L: {
    id: 'L',
    code: 'L',
    name: '问天研究实验室',
    subtitle: '知识 · 科技 · 量子计算核心',
    role: 'research',
    unlockYear: 22,
    requiredTech: 'TL-0',
    maxLevel: 15,
    baseUpgradeCost: { alloy: 6, currency: 6 },
    yieldGrowth: 0.1,
    priority: 9,
    reserveFloor: { power: 10, quantumCore: 1 },
    interfaceDuty: '特殊设施页展示科技界面。',
    note: '可以解锁科技；前期产出知识，后期在相关科技解锁后可生产量子计算核心。',
    productionMethods: [
      { id: 'ML-1', name: '基础研究', input: { power: 0.8 }, output: { knowledge: 2.4 }, note: '前期主要产出知识。' },
      { id: 'ML-2', name: '原子阵列光刻', input: { power: 1.8, water: 0.5, oxygen: 0.5, alloy: 0.8 }, output: { knowledge: 1.6, quantumCore: 0.6 }, unlockedBy: 'TL-1', note: 'TL-1 解锁后生产量子计算核心。' },
    ],
    phaseNotes: [
      { name: '前期', note: '主要产出知识。' },
      { name: '后期', note: '相关科技解锁后，可生产量子计算核心。' },
    ],
  },
  H: {
    id: 'H',
    code: 'H',
    name: '翡翠宫',
    subtitle: '中期人口 · 艺术奢侈品',
    role: 'culture',
    unlockYear: 26,
    requiredTech: 'TH-0',
    maxLevel: 12,
    baseUpgradeCost: { alloy: 6, biomass: 5 },
    yieldGrowth: 0.07,
    priority: 5,
    reserveFloor: { biomass: 6 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '中期人口建筑。翡翠宫是月面上最不实用的东西——它消耗更多资源，但产出艺术奢侈品。陈林批准建造时，述职报告里写的是"文化软实力"，心里想的是"有朝一日能卖给罗莎"。',
    productionMethods: [
      { id: 'MH-1', name: '宫廷居住与供养', input: { water: 0.5, oxygen: 0.4, biomass: 0.5 }, output: { population: 1, luxury: 0.9 }, note: '中期人口容量建筑。宫廷居民消耗更高，但会按居住人口产出艺术奢侈品。' },
    ],
  },
  M: {
    id: 'M',
    code: 'M',
    name: '新月府',
    subtitle: '后期人口 · 低消耗',
    role: 'habitat',
    unlockYear: 30,
    requiredTech: 'TM-0',
    maxLevel: 10,
    baseUpgradeCost: { alloy: 18, regolith: 16, water: 8 },
    yieldGrowth: 0.05,
    priority: 6,
    reserveFloor: { population: 10 },
    interfaceDuty: '展示光伏配方、当前产量、规模与扩建成本。',
    note: '后期人口建筑。新月府的生态居民包单位消耗更低，但需要月穹生态环完成后才能解锁。陈林在图纸上的批注是："先让月面能呼吸，再让人住得像人。"',
    productionMethods: [
      { id: 'MM-1', name: '新月府生态居住', input: { water: 0.2, oxygen: 0.2, biomass: 0.3 }, output: { population: 1.2 }, note: '后期人口容量建筑。生态居民生命维持消耗更低，人口增长由全局人口系统结算。' },
    ],
  },
  D: {
    id: 'D',
    code: 'D',
    name: '冠冕星舰坞',
    subtitle: '胜利目标 · 御座号建造项目',
    role: 'ship',
    unlockYear: 48,
    requiredTech: 'TD-0',
    maxLevel: 10,
    baseUpgradeCost: { alloy: 80, currency: 2 },
    yieldGrowth: 0.04,
    priority: 16,
    reserveFloor: { power: 14, alloy: 12, quantumCore: 2, currency: 6 },
    interfaceDuty: '展示御座号项目进度、三阶段物资供应、人力供应与胜利条件。',
    note: '胜利目标建筑。冠冕星舰坞账面上是"垦殖成果展示项目"，实际上是御座号的建造地。陈林每天都会来看龙骨进度——不是出于责任感，是出于想回家。',
    productionMethods: [
      { id: 'MD-1', name: '远洋星舰建造', input: { power: 45, water: 5, oxygen: 18, biomass: 16, regolith: 12, alloy: 20 }, output: {}, note: '项目型生产方式。按日消耗电力、合金、氧气和深空补给材料，不产出普通库存资源。实际胜利投入分为三阶段，由星舰界面展示。' },
    ],
    phaseNotes: [
      { name: '第一阶段：龙骨与生命舱', note: '投入合金、氧气和电力。龙骨对准太渊方向，像一根想要刺穿天穹的刺。' },
      { name: '第二阶段：远航壳层与循环农场', note: '投入合金、电力、月壤和生物质。远航壳层让御座号能撑过深空，循环农场让乘客能活着撑过去。' },
      { name: '第三阶段：王座核心与深空储备', note: '投入量子计算核心、电力、合金、水和生物质。王座核心是御座号的心脏——陈林给它取了这个名字，因为他终于要离开一把龙椅，登上另一把。' },
    ],
  },
}

export const facilityOrder: FacilityId[] = ['E1', 'C1', 'K', 'B', 'E2', 'C2', 'F', 'P', 'R', 'L', 'H', 'M', 'S', 'E3', 'D']

export const shipProjectStages: ShipProjectStage[] = [
  {
    id: 1,
    name: '龙骨与生命舱',
    input: { alloy: 8000, oxygen: 6000 },
    note: '第一阶段投入合金、氧气和电力，完成星舰基础结构与维生舱段。',
  },
  {
    id: 2,
    name: '远航壳层与循环农场',
    input: { alloy: 16000, regolith: 30000, biomass: 12000 },
    note: '第二阶段投入合金、电力、月壤和生物质，完成长期远航壳层与生态循环。',
  },
  {
    id: 3,
    name: '王座核心与深空储备',
    input: { quantumCore: 16, alloy: 24000, water: 12000, biomass: 18000 },
    note: '第三阶段投入量子计算核心、电力、合金、水和生物质，完成御座号核心。',
  },
]
