import type { EventChain } from './types'

export const eventChains: EventChain[] = [
  {
    id: 'sava-catalyst',
    roleId: 'sava',
    arc: 'simple',
    stage: 'early',
    events: [{
      id: 'sava-1',
      title: '逆燃晶体',
      body: '萨瓦献上一枚向内塌缩的晶体，它燃烧时不发光，反而吞光。她要求一批月面水样校准光谱，说这颗石头认得水。',
      interaction: 'techTrade',
      offer: { give: { quantumCore: 3, knowledge: 6 }, take: { water: 6 }, tech: 'TE1-1 纳米光催化剂' },
    }],
  },
  {
    id: 'melu-waterless',
    roleId: 'melu',
    arc: 'simple',
    stage: 'early',
    events: [{
      id: 'melu-1',
      title: '干燥孢囊',
      body: '梅露把一枚琥珀孢囊放在月尘里。它没有寻找水，而是把月壤咬开，从中抽出一层细小的根——孢囊里封着的，是一整段不需要雨的生态记忆。',
      interaction: 'gift',
      offer: { give: { oxygen: 12, biomass: 8 }, take: {}, tech: 'TB-2 无水栽培技术' },
    }],
  },
  {
    id: 'orri-leviathan',
    roleId: 'orri',
    arc: 'long',
    stage: 'late',
    events: [
      {
        id: 'orri-1',
        title: '无重力的骨骼',
        body: '欧里请求查看星舰坞的龙骨图。他没有索要报酬，只说某些骨骼必须先学会遗忘月球，否则飞不远。他悬浮在龙骨上方，银灰潮汐轻轻拍打着合金。',
        interaction: 'rareTrade',
        offer: { give: { alloy: 22, quantumCore: 2 }, take: { regolith: 8, power: 12 } },
      },
      {
        id: 'orri-2',
        title: '潮汐校准',
        body: '他要求一次高能潮汐试验，没有给出明确保证。只有舱壁上逐渐变低的振动声，和太渊金光在龙骨表面缓慢爬行的轨迹。',
        interaction: 'accident',
        concealed: true,
        rolls: [
          { give: { quantumCore: 1 }, take: { power: 10 } },
          { give: {}, take: { alloy: 8, power: 6 } },
        ],
      },
      {
        id: 'orri-3',
        title: '黑洞约束箴言',
        body: '欧里终于说出他携带的真正遗产：一套把微型黑洞系在掌心的约束箴言。他说这是轨道鲸一族的送嫁之物——她们把最危险的东西送给最想逃跑的人。',
        interaction: 'techTrade',
        offer: { give: { quantumCore: 2 }, take: { alloy: 12, power: 12 }, tech: 'TE3-0 外星科技：微型黑洞约束' },
      },
    ],
  },
  {
    id: 'nix-labor',
    roleId: 'nix',
    arc: 'simple',
    stage: 'mid',
    events: [{
      id: 'nix-1',
      title: '退役礼仪机的名册',
      body: '尼克斯带来一份劳工契约名册，要求这笔交易必须在星海交易港登记。他的黄铜面孔上，七层旧主徽记同时闪烁了一下，仿佛在替他行礼。',
      interaction: 'starportTrade',
      offer: { give: { knowledge: 14, currency: 8 }, take: { alloy: 10 }, tech: 'TS-1 星际劳工' },
      note: '固定在星海交易港添加人口 / 劳工双向贸易权限。',
    }],
  },
  {
    id: 'taro-alchemy',
    roleId: 'taro',
    arc: 'simple',
    stage: 'mid',
    events: [{
      id: 'taro-1',
      title: '小行星矿脉图',
      body: '塔罗展开一张用石英皮肤拓下来的矿脉图。图上有一段不像自然形成的炼金注释，他说是某颗死去的小行星临终前刻在自己骨头上的。',
      interaction: 'techTrade',
      offer: { give: { regolith: 30, alloy: 9 }, take: { oxygen: 7 }, tech: 'TF-1 重原子炼金术' },
    }],
  },
  {
    id: 'evi-echo',
    roleId: 'evi',
    arc: 'simple',
    stage: 'mid',
    events: [{
      id: 'evi-1',
      title: '回声接入',
      body: '伊芙请求接入王冠扬声器。她说知识会以回声抵达，但回声总会带走一点什么——可能是噪音，可能是寂静，也可能是一段你不想被听见的心事。',
      interaction: 'accident',
      concealed: true,
      rolls: [
        { give: { biomass: 10, luxury: 8 }, take: { power: 9 }, tech: 'TS-2 知识传输协议' },
        { give: { knowledge: 16 }, take: { power: 12 }, tech: 'TS-2 知识传输协议' },
      ],
    }],
  },
  {
    id: 'rosa-luxury',
    roleId: 'rosa',
    arc: 'simple',
    stage: 'mid',
    events: [{
      id: 'rosa-1',
      title: '玫瑰星球账册',
      body: '罗莎的袖口封着香料账册，行走间有花瓣碎裂的气味。她愿意让月面王国进入玫瑰星球的奢侈品航线，但她的微笑里有一句没说出口的话：你们目前还买不起。',
      interaction: 'starportTrade',
      offer: { give: { luxury: 12, currency: 12 }, take: { biomass: 8, knowledge: 4 }, tech: 'TS-3 玫瑰星球' },
      note: '固定在星海交易港添加艺术奢侈品双向贸易权限。',
    }],
  },
  {
    id: 'atya-refuge',
    roleId: 'atya',
    arc: 'long',
    stage: 'mid',
    events: [
      {
        id: 'atya-1',
        title: '家园落难的幸存者',
        body: '阿缇娅和她的族人请求留在月面。她们没有武器，只有一枚记录家园坐标的核——核还在发热，说明家园沦陷的时间不远。',
        interaction: 'request',
        offer: { give: { population: 1 }, take: { oxygen: 4, biomass: 4 } },
      },
      {
        id: 'atya-2',
        title: '追兵抵达',
        body: '一支陌生舰队要求交出幸存者。阿缇娅没有辩解，只把坐标核推到王座前。太渊的金光从舷窗照进来，在她烧焦的聚合毯上投下一道不像属于这颗卫星的暖色。',
        interaction: 'chainChoice',
        offer: { give: {}, take: { currency: 10, alloy: 8 } },
      },
      {
        id: 'atya-3',
        title: '伊甸园坐标',
        body: '赎金换来了时间。数年后，坐标核完成解密：那里不是墓碑，而是一颗仍能呼吸的生态行星。阿缇娅没有说话，只是第一次在月面上流下了不冻的泪。',
        interaction: 'techTrade',
        offer: { give: { water: 8, biomass: 8 }, take: {}, tech: 'TC2-2 发现伊甸园' },
      },
    ],
  },
]
