import type { Role } from './types'

export const roles: Role[] = [
  {
    charId: 'char-01',
    id: 'sava',
    name: '萨瓦·碎光',
    species: '折光甲壳人 / 来自太渊内侧第三轨道',
    glyph: '◈',
    portrait: '冰裂色甲壳在太渊金光下折射出冷蓝纹路，掌中托着一枚向内塌缩燃烧的晶体',
    specialty: 'E1',
    boost: 0.05,
    retainerCost: { water: 2, currency: 4 },
    quote: '“你们把恒星装进了贡箱，我可以让它少吃一点——但别指望它感恩。”',
  },
  {
    charId: 'char-02',
    id: 'melu',
    name: '梅露·第九孢',
    species: '浮游菌落使节 / 来自太渊环带孢子云',
    glyph: '❋',
    portrait: '以琥珀孢囊维持人形，靠近时能听见孢壁内细密的雨声，像一颗被封装的生态',
    specialty: 'B',
    boost: 0.06,
    retainerCost: { biomass: 3, currency: 3 },
    quote: '“土壤记得每一位被埋葬的王。你们的还很年轻——年轻到仍然以为活着是理所当然。”',
  },
  {
    charId: 'char-03',
    id: 'orri',
    name: '欧里·无重力',
    species: '轨道鲸后裔 / 来自太渊引力阱外缘',
    glyph: '☾',
    portrait: '一团悬浮的银灰潮汐，没有固定骨骼，发声时舱壁会随其低频共振而微微颤抖',
    specialty: 'D',
    boost: 0.06,
    retainerCost: { alloy: 8, quantumCore: 1 },
    quote: '“星舰的骨骼不该只记得重力，也要记得离开它。你那位王，他的脚记得太牢了。”',
  },
  {
    charId: 'char-04',
    id: 'nix',
    name: '尼克斯·二十七',
    species: '退役礼仪机 / 产地不明，太渊星域旧制式',
    glyph: '⌘',
    portrait: '黄铜面孔上七位旧主徽记层层覆盖，最底层的王徽仍在缓慢闪烁，像不肯熄灭的效忠',
    specialty: 'K',
    boost: 0.04,
    retainerCost: { currency: 6 },
    quote: '“我曾侍奉过七位不朽君主，结果都差不多。你看上去比他们清醒，这未必是好事。”',
  },
  {
    charId: 'char-05',
    id: 'taro',
    name: '塔罗·掘井者',
    species: '硅酸盐游牧民 / 来自太渊外环碎屑带',
    glyph: '◇',
    portrait: '石英皮肤上刻满失落小行星的矿脉图，指尖触地时能感知月面深处缓慢的应力',
    specialty: 'C1',
    boost: 0.05,
    retainerCost: { regolith: 10, oxygen: 2 },
    quote: '“月亮不是死的，只是它把话说得很慢。你们踩在上面，却从来没弯下耳朵听过。”',
  },
  {
    charId: 'char-06',
    id: 'evi',
    name: '伊芙·回声',
    species: '声学群体 / 来自太渊磁层共振腔',
    glyph: '≈',
    portrait: '数十条细小波纹在王冠形扬声器中彼此回答，没有身体，只有被器物收容的共鸣',
    specialty: 'H',
    boost: 0.04,
    retainerCost: { knowledge: 6, luxury: 2 },
    quote: '“我听见你们把孤独叫作秩序，所以来收集一点。孤独是会回声的，你们知道吗？”',
  },
  {
    charId: 'char-07',
    id: 'rosa',
    name: '罗莎·花冠',
    species: '玫瑰星球商团 / 来自太渊跃迁走廊另一端',
    glyph: '✦',
    portrait: '礼服像一层会呼吸的薄雾，袖口封着来自玫瑰星球的香料账册，行走间有花瓣碎裂的气味',
    specialty: 'S',
    boost: 0.05,
    retainerCost: { luxury: 4, currency: 8 },
    quote: '“奢侈品不是多余之物。它们是文明愿意承认自己仍有余裕——你治下的月面，目前还没有这个余裕。”',
  },
  {
    charId: 'char-08',
    id: 'atya',
    name: '阿缇娅·灰舟',
    species: '流亡栖居者 / 原籍伊甸星系，家园已沦陷',
    glyph: '✧',
    portrait: '披着烧焦的聚合毯，怀中抱着一枚仍在发热的家园坐标核，眼底有被追了很久的人特有的警觉',
    specialty: 'C2',
    boost: 0.04,
    retainerCost: { oxygen: 6, biomass: 6 },
    quote: '“请别把我们交回黑夜。我们知道一颗还活着的行星在哪里——它比这颗石头温柔得多。”',
  },
]
